name: "Helm Chart Releaser"
description: "Host a Helm charts repo on GitHub Pages"
author: "The Helm authors"
branding:
  color: blue
  icon: anchor
inputs:
  version:
    description: "The chart-releaser version to use (default: v1.0.0-beta.1)"
  charts_dir:
    description: The charts directory
    default: charts
  charts_repo_url:
    description: "The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)"
    required: true
runs:
  using: "node12"
  main: "main.js"
