name: "Helm Chart Releaser"
description: "Host a Helm charts repo on GitHub Pages"
author: "The Helm authors"
branding:
  color: blue
  icon: anchor
inputs:
  version:
    description: "The chart-releaser version to use (default: v1.1.1)"
  config:
    description: "The relative path to the chart-releaser config file"
  charts_dir:
    description: The charts directory
    default: charts
  charts_repo_url:
    description: "The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)"
  release_name_template:
    description: "Go template for computing release names, using chart metadata (default '{{ .Name }}-{{ .Version }}')"
runs:
  using: composite
  steps:
    - run: |
        owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
        repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")

        args=(--owner "$owner" --repo "$repo")
        args+=(--charts-dir "${{ inputs.charts_dir }}")

        if [[ -n "${{ inputs.version }}" ]]; then
            args+=(--version "${{ inputs.version }}")
        fi

        if [[ -n "${{ inputs.config }}" ]]; then
            args+=(--config "${{ inputs.config }}")
        fi

        if [[ -n "${{ inputs.charts_repo_url }}" ]]; then
            args+=(--charts-repo-url "${{ inputs.charts_repo_url }}")
        fi

        if [[ -n "${{ inputs.release_name_template }}" ]]; then
            args+=(--release-name-template "${{ inputs.release_name_template }}")
        fi

        "$GITHUB_ACTION_PATH/cr.sh" "${args[@]}"
      shell: bash
