apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80    
      targetPort: 1080
      name: tcp1
    - protocol: TCP
      port: 25    
      targetPort: 1025
      name: tcp2
