name: Keep the major version tag up-to-date
on:
  release:
    types: [published]

permissions:
  contents: write

# move the major version tag to the latest release, e.g., v1, to enable
# consumers to subscribe to the latest reverse-compatible release
jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: false
          prefer_branch_releases: false 
