name: test-chart-releaser

on:
  pull_request:

permissions: {}

jobs:

  test_chart_releaser_install_action:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    name: Install chart-releaser and test presence in path
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install chart-releaser
      uses: ./
      with:
        install_only: true
      env:
        CR_TOKEN: "FAKE_SECRETS"
    - name: Check install!
      run: |
        cr version
        CR_VERSION_OUTPUT=$(cr version 2>&1 /dev/null)
        ACTUAL_VERSION=$(echo "$CR_VERSION_OUTPUT" | grep GitVersion | rev | cut -d ' ' -f1 | rev)
        if [[ $ACTUAL_VERSION != 'v1.7.0' ]]; then
          echo 'should be v1.7.0'
          exit 1
        else
          exit 0
        fi
      shell: bash
    - name: Check root directory
      run: |
        if ! git diff --stat --exit-code; then
          echo 'should be clean'
          exit 1
        fi

  test_chart_releaser_action:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    name: Install chart-releaser and run it
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install chart-releaser
      uses: ./
      env:
        CR_TOKEN: "FAKE_SECRETS"
    - name: Check root directory
      run: |
        if ! git diff --stat --exit-code; then
          echo 'should be clean'
          exit 1
        fi
